"""runs minimal

Revision ID: 95167e094824
Revises: a6d4f76fdda1
Create Date: 2025-09-13 21:49:57.102848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95167e094824'
down_revision = 'a6d4f76fdda1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('suite_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('csv_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suite_id'], ['suites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_suite_id'), ['suite_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_suite_id'))
        batch_op.drop_index(batch_op.f('ix_runs_project_id'))

    op.drop_table('runs')
    # ### end Alembic commands ###
