"""suites only

Revision ID: a6d4f76fdda1
Revises: 
Create Date: 2025-09-13 20:51:03.544276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d4f76fdda1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['suites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'parent_id', 'slug', name='uq_suite_slug_per_parent')
    )
    with op.batch_alter_table('suites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suites_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suites_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suites_project_id'))
        batch_op.drop_index(batch_op.f('ix_suites_parent_id'))

    op.drop_table('suites')
    # ### end Alembic commands ###
